//Nessa requisição basta passar o CEP como parâmetro na URL
//Ex: localhost:8081/consulta?cep={cep}
GET http://localhost:8081/consulta?cep=08223110 HTTP/1.1
Host: localhost:8081
Content-Type: application/json
